### ISSUE TITLE
For those who are not familiar with programming, how to use this program? Is there a user manual available?

### ISSUE THREAD

**Issue by qihuoren** [hammadtariq838/WhisperSync#1]
Using the Whisper API for transcription and translation, would using the Chat GPT API result in more accurate subtitle translations? 

The Whisper API has a size limit of 25MB. Does it support long videos? One possible solution I can think of is compressing the audio to increase the time limit for longer videos, or segmenting and merging them after recognition. Has this issue been addressed?

**Comment by hammadtariq838** [comment]
The Whisper API consistently delivers exceptional results, particularly for English transcription. While it may require some manual verification and adjustments for subtitles, it serves as an excellent starting point. It's worth noting that even third-party APIs rely on machine learning models to achieve similar outcomes.

Regarding the size limit, I acknowledge this constraint. I plan to implement compression techniques to mitigate the issue. However, it is possible that achieving the desired size without significant quality degradation could impact the accuracy of subtitle generation. To address this, I intend to break the compressed audio into manageable chunks for transcription. However, I am currently conducting research on this matter, as it is crucial to consider the continuity of sentences, phonemes, and dialects while dividing the audio. These factors will be taken into account during the implementation process.

**Comment by qihuoren** [comment]
For those who are not familiar with programming, how to use this program? Is there a user manual available?

**Comment by hammadtariq838** [comment]
@qihuoren, I would like to inform you that I am currently working on the Minimum Viable Product (MVP), which is expected to be completed within the next few days. Once it is ready, I will promptly share the live website link with you and also update it in the README.md file. You will be able to register and interact with the program on the website. Regarding your question about a user manual, I have not yet made specific plans for creating one, as the web application is designed to be straightforward and intuitive to use. Therefore, I do not anticipate any significant issues with using the application. Thank you for your understanding and please feel free to reach out if you have any further inquiries.

Regards,
Muhammad Hammad
